#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

//! SIGNALS

/*
Signals can be generated by a user programmatically to be
sent by the OS.

A signal can be generated by calling raise() or kill() system calls
    * raise() sends a signal to the current process
    * kill() sends a signal to a specific process

alarm() provides a mechanism for a process to interrupt itself in the future
*/

#include <signal.h>

int main()
{
    /*
    printf("Testing SIGSTOP\n");
    raise(SIGSTOP); // ctrl + z
    printf("It stopped?\n\n");
    */
    alarm(5); //will generate a signal after 5 seconds an terminate the program

    for(int i = 1; i<10; i++){
        printf("%d\n", i);
        sleep(1);
    }
    return 0;
}
